repos:
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ['--fix=lf']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-commas',
        'flake8-comprehensions',
        'flake8-deprecated',
        'flake8-docstrings',
        'flake8-meiqia',
        'flake8-mutable',
        'flake8-pep3101',
        'flake8-quotes',
        'flake8-string-format',
        'flake8-tidy-imports',
        ]
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
-   repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v0.942
    hooks:
    -   id: mypy
        args: [--strict, --config-file, .mypy.ini, --follow-imports=normal]
        additional_dependencies: [typer, numpy, pandas, pytest, tk, pydantic]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: python
        args: ["-j 0"]
        types:
          - python
    -   id: doctest
        name: doctest
        entry: python -m doctest
        args: [-v]
        language: system
        types: [python]
        pass_filenames: True
