#!/bin/bash

# Update pip
python -m pip install --upgrade pip setuptools wheel

# Install pre-commit
python -m pip install --upgrade pre-commit
pre-commit install --install-hooks
pre-commit autoupdate

# Install pylint
python -m pip install --upgrade pylint
pylint --generate-rcfile > ~/.pylintrc

# Install positron_cross_section
python -m pip install -e positron_cross_section

echo "Congratulations! The Positron Cross Section Analysis application is now installed."
