# This workflow will install the program and run the pre-commit linting/testing with python 3.8

name: Pre-commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        source tools/install-dev-env
        sudo apt update && sudo apt install tk -y
    - name: Run pre-commit
      run: |
        pre-commit run --all-files --hook-stage push
